import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TopNav from "./ui/topnav";
import './ui/globals.scss'; //the globals.scss file contains the tailwind utility classes that enable tailwind keywords to work
import BottomNav from "./ui/bottomnav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <TopNav />
        {children}
        <BottomNav />
      </body>
    </html>
  );
}
